spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/admin,/users/**,/users,/categories/**,/categories,/compilations/**,/compilations,/events/**,/events,/comments/**,/comments
          filters:
            - name: Retry
              args:
                retries: 3

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info